### ISSUE TITLE
主页无法正常加载用户头像、博客名称

### ISSUE THREAD

**Issue by ValentinLiu15** [mytinfeng/StarrySky#3]
环境：
Nginx 1.21.4（OpenSSL 1.1.1l）
PHP 8.0
Typecho 1.2.0 RC

主页无法正常加载用户头像、博客名称。
使用 F12 查看，博客头像的属性显示为“src(unknow)”正常应为“src="xxx"”

**Comment by mytinfeng** [comment]
在主题外观设置即可
