### ISSUE TITLE
独立页面无法显示内容

### ISSUE THREAD

**Issue by ValentinLiu15** [mytinfeng/StarrySky#4]
独立页面无法显示内容
根据五个模板新建了五个对应的独立页面
但是独立页面无法显示内容

**Comment by ValentinLiu15** [comment]
https://levimarvin.site

**Comment by ValentinLiu15** [comment]
“关于”和“其他”
“友链”暂未测试
“归档”显示正常（上面快速选择年份按钮太亮啦 有点和背景违和）

**Comment by mytinfeng** [comment]
> “关于”和“其他” “友链”暂未测试 “归档”显示正常（上面快速选择年份按钮太亮啦 有点和背景违和）

关于和其它友情链接，需要自己写内容呢，如果遇到问题，可以🐧找我会比较快得到解决

**Comment by ValentinLiu15** [comment]
当然是自己写了内容的啦，第一个issue是我没看readme，没按教程走，但这次不是呀（

**Comment by ValentinLiu15** [comment]
而且你的🐧是多少呀

**Comment by mytinfeng** [comment]
> 而且你的🐧是多少呀

啊。忘记放演示站了 blog.owoii.com
在这里面可以找到我的🐧

**Comment by ValentinLiu15** [comment]
加了哦
